services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bakery
      - POSTGRES_PASSWORD=bakery
      - POSTGRES_DB=bakery

  redis:
    image: redis:latest
    container_name: mrfixit_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: /bin/sh -c "redis-server --requirepass ${APP_REDIS_PASSWORD}"
    env_file:
      - .env
