services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bakery
      - POSTGRES_PASSWORD=bakery
      - POSTGRES_DB=bakery
