pytest_plugins = (
    "tests.plugins.instances.db",
    "tests.plugins.instances.services",
    "tests.plugins.instances.storages",
    "tests.plugins.factories.user",
    "tests.plugins.factories.product",
    "tests.plugins.factories.pickup_address",
    "tests.plugins.factories.cart",
    "tests.plugins.factories.order",
    "tests.plugins.factories.order_schedule",
    "tests.plugins.factories.admin_contact",
    "tests.plugins.factories.delivery_cost",
    "tests.plugins.factories.order_payment",
    "tests.plugins.factories.feedback_group",
)
