from typing import Final

NEXT: Final = "Продолжить ➡️"
PREV: Final = "⬅️ Назад"
SEARCH: Final = "🔎 Поиск"
BACK: Final = "⬅️ Назад"
ADD: Final = "➕ Добавить"
REMOVE: Final = "➖ Убрать"
QUANTITY_DEC: Final = "➖"
QUANTITY_INC: Final = "➕"
SHARE: Final = "📤 Поделиться"
CREATE: Final = "✅ Создать"
UPDATE: Final = "✅ Обновить"
CANCEL: Final = "❌ Отмена"
DELETE: Final = "🗑 Удалить"
DELETE_REDUCED: Final = "🗑"
EDIT: Final = "✏️ Редактировать"
SAVE: Final = "✅ Сохранить"
SKIP: Final = "⏩ Пропустить"
YES: Final = "✅ Да"
NO: Final = "❌ Нет"
MAIN_MENU: Final = "🏠 На главную"
RESET: Final = "🔄 Сбросить"
CART: Final = "🧺 К корзине"
ORDERS_IN_PROGRESS: Final = "🛠 Готовятся"
