from typing import Final

NEXT: Final = "Продолжить ➡️"
BACK: Final = "🔙 Назад"
ADD: Final = "➕ Добавить"
SHARE: Final = "📤 Поделиться"
CREATE: Final = "✅ Создать"
UPDATE: Final = "✅ Обновить"
CANCEL: Final = "❌ Отмена"
DELETE: Final = "🗑 Удалить"
EDIT: Final = "✏️ Редактировать"
SAVE: Final = "✅ Сохранить"
SKIP: Final = "⏩ Пропустить"
YES: Final = "✅ Да"
NO: Final = "❌ Нет"
MAIN_MENU: Final = "🏠 На главную"
