"""empty message

Revision ID: f24ca5b5fee6
Revises:
Create Date: 2025-06-04 17:02:26.500948

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f24ca5b5fee6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=63), nullable=False),
        sa.Column("tg_id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column(
            "role", postgresql.ENUM("admin", "user", name="user_role"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__users")),
    )
    op.create_index(
        op.f("ix__users__phone"),
        "users",
        ["phone"],
        unique=True,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_index(
        op.f("ix__users__tg_id"),
        "users",
        ["tg_id"],
        unique=True,
        postgresql_where="deleted_at IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix__users__tg_id"),
        table_name="users",
        postgresql_where="deleted_at IS NULL",
    )
    op.drop_index(
        op.f("ix__users__phone"),
        table_name="users",
        postgresql_where="deleted_at IS NULL",
    )
    op.drop_table("users")
    # ### end Alembic commands ###
